# This is a basic workflow to help you get started with Actions

name: test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: |
            make
            ./test/test
